### ISSUE TITLE
Can't update component after button click

### ISSUE THREAD

**Issue by Lupusa87** [Lupusa87/LupusaBlazorProjects#13]
I have some page and inside my **custom component**.
Custom component should receive Rawhtml parameter from user input.

After button click result is not updating in UI.

How can I pass new value to component after input and button click?

Tried several approaches but can't solve.

```
@page "/rawhtml"
@addTagHelper *, BlazorLib3
@using BlazorLib3

    <input bind="@htmlString" type="text" placeholder="enter raw html" />

    <button class="btn btn-primary" onclick="@cmd_convert">Run</button>
 
    <div>
       <ComponentRawHTML RawHTML="@htmlString"></ComponentRawHTML>
    </div>

@functions{
    string htmlString = "<h2>hello</h2>";

    void cmd_convert()
    {
        StateHasChanged();
    }

}
```

**Comment by Lupusa87** [comment]
Using this approach solved problem
https://github.com/EdCharbeneau/BlazeDown/blob/master/MarkdownComponent/Markdown.cshtml

But I wonder why I can't update UI with my approach, what is problem?

**Comment by bmsantos** [comment]
@Lupusa87, I don't know why your approach does not work. I'm pretty new to Razor pages myself.

Assuming that "StateHasChanged()" method actually does change the bound "htmlstring", I don't see why your approach does not work.

One other option you might want to consider is to have a MessagingService in the middle: https://github.com/bmsantos/RxBlazor

**Comment by Lupusa87** [comment]
Thank you.
I will return to this issue later and give you notice if I will fix it.
