### ISSUE TITLE
TreeView images?

### ISSUE THREAD

**Issue by ZedZipDev** [Lupusa87/LupusaBlazorProjects#17]
Thank you, great components.
How to display TreeView nodes with images? 
With images from database?

**Comment by Lupusa87** [comment]
Hi, you want tree items to have icons?
It should be easy to do, I will check later today and will let you know :)

**Comment by Lupusa87** [comment]
Re dayabase this is external, you will load them and then set as parameter to treeview.
How to load from db depends on your architecture.
I guess You will get it using http calls to your backend.

**Comment by ZedZipDev** [comment]
> Hi, you want tree items to have icons?
> It should be easy to do, I will check later today and will let you know :)

Yes, exactly. To display different nodes, node types etc with their images. Thanx.

**Comment by Lupusa87** [comment]
Will check tomorrow or Monday and will get back.

**Comment by Lupusa87** [comment]
Hi @Oleg26Dev I added icons, you can see below and also in code https://github.com/Lupusa87/LupusaBlazorDemos/tree/master/BlazorTreeVisualizerComponent

![Untitled](https://user-images.githubusercontent.com/40779557/82963673-762daa80-9f91-11ea-824a-e3a1debbf78e.png)

**Comment by ZedZipDev** [comment]
great, thanx!
