### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by DmitriiKh** [Lupusa87/LupusaBlazorProjects#18]
Hi,
I really love to see that the live demo for [LoadFile ](https://lupblazordemos.z13.web.core.windows.net/PageLoadFile) works perfectly.

Unfortunately, I could not use your code from the [demo ](https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/Demos/PageLoadFile.razor.cs) as can not understand for example where LBDJsInterop comes from.

If your code was documented better I would definitely choose it over Tewr.Blazor.FileReader

Thank you for your work.

**Comment by ZedZipDev** [comment]
I use SteveSandersonMS/BlazorInputFile

**Comment by DmitriiKh** [comment]
@Oleg26Dev I tried the SteveSandersonMS/BlazorInputFile but I ran into this [large files issue](https://github.com/SteveSandersonMS/BlazorInputFile/issues/17) which exists since November by the way.

**Comment by Lupusa87** [comment]
https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/LBDJsInterop.cs

**Comment by Lupusa87** [comment]
https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/wwwroot/LBDJsInterop.js

**Comment by Lupusa87** [comment]
Hi guys, thank you.
@DmitriiKh  LBD is short of LupusaBlazorDemos.
LDB is main app which uses referenced library for fast js interop. It is in another repo and on nuget too.
I will answer better later from my PC, not at home now.
No problem I will do my best for you.

**Comment by Lupusa87** [comment]
https://github.com/Lupusa87/BlazorJsFastDataExchanger/blob/master/README.md

**Comment by DmitriiKh** [comment]
@Lupusa87 Thanks a lot. I am going to try using it on Monday.

**Comment by Lupusa87** [comment]
Hello @DmitriiKh I recorded [video](https://www.youtube.com/watch?v=0RFa8FNE9d0) available on youtube where I explain how file load is working.

Sorry, I know it is not best video because my English is not good but I hope you will get point how it works.

Best regards.
