### ISSUE TITLE
How to build the Demo app?

### ISSUE THREAD

**Issue by ZedZipDev** [Lupusa87/LupusaBlazorProjects#20]
The Demo app still cannot be built.
Ok, I am trying to build the separate project which uses BlazorTreeViewComponent only.

`error CS0246: The type or namespace name 'BlazorWindowHelper' could not be found`

I could not find the BlazorWindowHelper in the projects and in NuGet packages too.

I am sure it will be great if you can create Demo App +NuGet Packages+absent projects.
For now it is imposible to build the Demo and naturally to include the BlazorTreeViewComponent to other app.
Thanx.

**Comment by Lupusa87** [comment]
https://github.com/Lupusa87/BlazorWindowHelper

it is not on nuget, you need to download and reference from demos app.

I know it is confusing but it is how I was able to have everything togather.

Sorry for inconvenience.
