### ISSUE TITLE
The tree Images displayed random

### ISSUE THREAD

**Issue by ZedZipDev** [Lupusa87/LupusaBlazorProjects#21]
The first time
![image](https://user-images.githubusercontent.com/25686753/83346404-51805c80-a31c-11ea-8d92-eae132ac55d9.png)

Then I do refresh and see this
![image](https://user-images.githubusercontent.com/25686753/83346426-84c2eb80-a31c-11ea-8a46-67b7a2e448f4.png)

After the next refresh
![image](https://user-images.githubusercontent.com/25686753/83346444-b2a83000-a31c-11ea-85af-350c1fa2cc3e.png)

**Comment by Lupusa87** [comment]
Hello, it is not bug, I do it on purpose.

check code [here](https://github.com/Lupusa87/LupusaBlazorDemos/blob/master/LupusaBlazorDemos/Demos/PageTreeVIew.razor.cs#L128)
